import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Privacy",
  description: "Privacy policy for AnchorShip NL.",
};

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Company"
      title="Privacy Policy"
      lastUpdated="September 3, 2026"
      intro="This page explains what information AnchorShip NL collects when you use this site, why, and what rights you have over it. It's a general-purpose template, written to match how the site is actually built today — update it as the data processors below change."
      sections={[
        {
          heading: "Who we are",
          body: (
            <p>
              AnchorShip NL (&ldquo;we&rdquo;, &ldquo;us&rdquo;) is the data controller for
              personal information submitted through this site. Questions about this policy can
              be sent through the{" "}
              <a href="/contact" className="font-medium text-blueprint">
                contact page
              </a>
              .
            </p>
          ),
        },
        {
          heading: "What we collect",
          body: (
            <>
              <p>We only collect what you give us directly, through one of three forms:</p>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  <span className="font-medium text-hull">Request a quote</span> — name, company,
                  email, phone (optional), the part number you&apos;re asking about, and any
                  message you add.
                </li>
                <li>
                  <span className="font-medium text-hull">Contact</span> — name, email, and your
                  message.
                </li>
                <li>
                  <span className="font-medium text-hull">Sell to us</span> — name, company,
                  email, phone (optional), and details of the equipment you&apos;re offering.
                </li>
              </ul>
              <p>
                We don&apos;t currently run analytics or advertising trackers on this site, so we
                don&apos;t collect browsing behaviour beyond standard web server logs (IP address,
                request time, page requested) kept briefly for security and debugging.
              </p>
            </>
          ),
        },
        {
          heading: "How we use it",
          body: (
            <p>
              Submitted information is used to respond to your enquiry, quote or value equipment,
              and — where an order or purchase goes ahead — to fulfil it. We don&apos;t sell your
              information, and we don&apos;t use it for marketing you haven&apos;t asked for.
            </p>
          ),
        },
        {
          heading: "Legal basis",
          body: (
            <p>
              We process form submissions on the basis of taking steps at your request prior to a
              possible contract (Art. 6(1)(b) GDPR), or our legitimate interest in responding to
              business enquiries (Art. 6(1)(f) GDPR) where no contract follows.
            </p>
          ),
        },
        {
          heading: "Who we share it with",
          body: (
            <>
              <p>
                We use a small number of processors to run the site and can share the minimum
                data each needs to do its job:
              </p>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  <span className="font-medium text-hull">Resend</span> — delivers the emails
                  generated by our forms.
                </li>
                <li>
                  <span className="font-medium text-hull">Neon</span> — hosts our database
                  (Postgres) and, where used, authentication.
                </li>
                <li>
                  <span className="font-medium text-hull">Cloudinary</span> — hosts and serves
                  listing photography; it does not receive your form submissions.
                </li>
              </ul>
              <p>We don&apos;t share your information with anyone beyond these processors.</p>
            </>
          ),
        },
        {
          heading: "Retention",
          body: (
            <p>
              We keep enquiry and submission records for as long as needed to handle your request
              and, where an order results, for the period required by Dutch tax and commercial
              record-keeping law. You can ask us to delete data that falls outside that
              requirement at any time.
            </p>
          ),
        },
        {
          heading: "Your rights",
          body: (
            <>
              <p>
                Under the GDPR, you can ask us to access, correct, delete, or export the personal
                data we hold on you, and you can object to or ask us to restrict how we use it.
                To exercise any of these, contact us via the{" "}
                <a href="/contact" className="font-medium text-blueprint">
                  contact page
                </a>
                .
              </p>
              <p>
                If you&apos;re not satisfied with our response, you have the right to lodge a
                complaint with the Dutch data protection authority (Autoriteit Persoonsgegevens).
              </p>
            </>
          ),
        },
        {
          heading: "Cookies",
          body: (
            <p>
              This site currently sets no analytics, advertising, or tracking cookies. If that
              changes, this section will be updated to describe what&apos;s set and how to opt
              out.
            </p>
          ),
        },
        {
          heading: "Changes to this policy",
          body: (
            <p>
              We&apos;ll update the &ldquo;last updated&rdquo; date at the top of this page
              whenever this policy changes materially.
            </p>
          ),
        },
      ]}
    />
  );
}
